# -*-Sh-*- <-- tells emacs what kind of syntax highlighting to use

echo ">>> BASH: Loading bash_aliases file..."

alias tunes="lsof | grep -i mp3"
alias viewlog='tail -f /var/log/httpd/access_log'

alias diffdir='diff -rq'


#alias vista='ssh alexcom@apollo.vistapages.com'
alias alexcom='ssh alexcom@alexwilliams.com'
#export VP=alexcom@apollo.vistapages.com

alias jig='ssh jig.cse.ucsc.edu'
alias hustle='ssh  hustle.cse.ucsc.edu'
alias disco='ssh  disco.cse.ucsc.edu' # -X

alias chacha='ssh -X chacha.cse.ucsc.edu'
alias jive='ssh -X   jive.cse.ucsc.edu'
alias tap='ssh       tap.cse.ucsc.edu'
alias bop='ssh       bop.cse.ucsc.edu'

alias moondance='ssh moondance.cse.ucsc.edu'
alias riverdance='ssh waterdance.cse.ucsc.edu'
alias waterdance='ssh waterdance.cse.ucsc.edu'
alias sundance='ssh sundance.cse.ucsc.edu'

alias treeviewmemory='java -Xmx999m -jar TreeView.jar'

alias z='echo $USER'

# Shell navigation / commands
alias      l='/bin/ls -F --color=auto'
alias     ls='/bin/ls -F --color=auto'
alias     ll='/bin/ls -lh -A -F --color=auto'
alias      h='history'
alias      p='pwd'
alias     tc='randomize_terminal_color.pl -cycle'
alias      b='cd ..'
alias     ..='cd ..'
alias    res='source ~/.bashrc ; source ~/.bash_profile'
alias     mv='mv -i'
alias     cp='cp -i'
alias    rrm='/bin/rm --verbose --preserve-root --interactive=once'
alias     rm='trash.pl'
alias checktrash='mkdir -p /tmp/$USER/Trash/ && echo "Contents of /tmp/$USER/Trash:" && ls /tmp/$USER/Trash/'
alias emptytrash='mkdir -p /tmp/$USER/Trash/ && /bin/rm -rf --preserve-root /tmp/$USER/Trash/ && echo "Emptied the trash directory (/tmp/$USER/Trash)" ;'
alias    kpk='exit'



#alias s='less -S --LINE-NUMBERS'

alias version="lsb_release -a" # Tells you which version of Ubuntu you are running!

alias res="source ~/.bashrc"


# Convert a Mac-style line-ending file to a UNIX one
# Useful for when you save a file in Excel and then UNIX won't read it.
function mac2unix {
    cat "$1" | tr '\r' '\n'
}

# Convert a Windows-style line-ending file to a UNIX one
# Useful for when you save a file in Excel and then UNIX won't read it.
function dos2unix {
    cat "$1" | tr -d '\r'
}




## Mac-specific commands:
alias invisible='SetFile -a V' ## Make a file/folder invisible to the Finder
alias visible='SetFile -a v' ## opposite of "invisible"

## Utility commands
alias    rr='screen -xR'
alias   wcl='wc -l'
alias sortt='sort -t "	"' # sort with tab as separator
alias sortg='sort -g -t "	"' # sort NUMBERS, with tab as separator
alias     e='emacs -nw'
alias     t='transpose.pl -q'
alias tattle="echo -n '\033[45m\033[33m'; ps aux | tail -n +2 | sort --reverse -k 3,3 | head -n 5 | perl -p -e 's/[ ]+/\t/g' | cut -f 1,3,4,11 | cap.pl 'USER,CPU,MEM,TASK' | sheet.pl \
--ht=75 --trunc=60 | tail -n +2 ; echo -n '\033[0m'"

# GNU Make-related
alias  make='make --warn-undefined-variables --print-directory'
alias     m='make'
alias   mcm='make clean && make'
function remake {
    ## Lets you type "remake" to remove a file and then use GNU make to try to re-generate it
	trash.pl "$1" && make --warn-undefined-variables --print-directory "$1"
}



# Aliases related to GREP
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Aliases related to CVS
alias commit="cvs commit -m 'AGW CVS Commit'"
alias gitcom="git commit -a -m 'Changes committed by alexgw'"
alias gitstat="git ls-files --modified --deleted"
alias gitdiff="git difftool"

alias hgcom="hg commit -u '$USER' -m 'Changes committed by $USER'"
alias hgpush="hg commit -u '$USER' -m 'Changes committed by $USER' && hg push"
alias hgpull="hg pull && hg update"
alias hgup="hg update"
alias hgs="hg status"

alias sciencecom='hg commit --cwd ${TIME_FOR_SCIENCE_DIR} -m "Changes committed by alexgw" && hg push --cwd ${TIME_FOR_SCIENCE_DIR}'
alias scienceup='hg --cwd ${TIME_FOR_SCIENCE_DIR} pull && hg --cwd ${TIME_FOR_SCIENCE_DIR} update'
alias sciencestat='hg --cwd ${TIME_FOR_SCIENCE_DIR} status'




# Things related to "LESS"
export LESSOPEN="|${TIME_FOR_SCIENCE_DIR}/Config/1_Shell_Config/lesspipe_basic.sh %s"
# lesspipe_basic.sh casues less to transparently decompress gzipped files before showing them
# Old:  '|/usr/bin/lesspipe.sh %s'

alias magicless='env LESSOPEN="|${TIME_FOR_SCIENCE_DIR}/Config/1_Shell_Config/lesspipe_advanced.sh %s" /usr/bin/less -S -f'
# It's less, but it "magically" handles gzipped files and automatically runs ".tab" files through sheet.pl
# Note that this only magically happens if the files are passed in on the command line--otherwise you have
# to use "ssf" to force sheet.pl to be run (if a file is passed through a pipe, then it won't be run through
# sheet.pl unless you say "cat something | ssf"

# Plain "sn" doesn't run anything through sheet.pl, but it *does* handle gzipped files
alias  sn='/usr/bin/less -S --LINE-NUMBERS --status-column --ignore-case -R -f'

function s {
    # "s" uses "magicless" to run files through sheet.pl
    magicless --LINE-NUMBERS --status-column --ignore-case -R $*
}

function sf {
    # Forces sheet.pl to be called ("SS Force sheet.pl").  Can only view ONE file, unlike "ss"
    /usr/bin/less $1 | sheet.pl | s
}

function s1 {
    # like sf, but shorter columns # Can only view ONE file, unlike "ss"
    /usr/bin/less $1 | sheet.pl --trunc=15 | s
}

function s2 {
    # like sf, but shorter columns # Can only view ONE file, unlike "ss"
    /usr/bin/less $1 | sheet.pl --trunc=25 | s
}

function  ltab {
    # Use sheet.py to view a file or list of files. These files cannot be gzipped, however.
    # Must be python2.6, and not python 3, currently
    python `which sheet.py` $*
}

alias v='ltab'

