# Runs the Python `pytest` unit tests.
SHELL := /bin/bash

# "test" is a rule that re-runs each time (it doesn't generate a file named 'test')
.PHONY: test
 
# If this fails, you may need to run "pip3 install pytest"
test:
	python3 -m pytest
 