#!/usr/bin/perl

## Note the plaintext password here!

use strict;
use warnings;

my $dfTemp = '/tmp/df.tmp';
my $sendTo = 'alexgraehl+lighthouse+status+update@gmail.com';

my $EMAIL_USERNAME_FROM = 'binfcore'; ## Do NOT include @gmail.com here!
my $PLAINTEXT_PASSWORD = undef;

if (!defined($PLAINTEXT_PASSWORD)) {
    print STDERR "Need to define the password...\n";
    exit(1);
}

my $HOSTNAME = `hostname`; # or uname-n
$HOSTNAME =~ s/^\s+//; $HOSTNAME =~ s/\s+$//; # remove trailing spaces, and then remove leading spaces

system(qq{echo 'Automatic status report from $HOSTNAME' > $dfTemp});

my $UPTIME = `uptime`;
system(qq{echo 'Automatic status report from $HOSTNAME' > $dfTemp});
system(qq{echo 'Generated by the script <email_df_status.pl>, which is symlinked in /etc/cron.weekly/' > $dfTemp});
system(qq{echo 'Uptime report: $UPTIME' >> $dfTemp});
system(qq{df >> $dfTemp}); ## save the df output to a file
system(qq{ email-smtp-client.pl }
       . qq{ --host=smtp.gmail.com }
       . qq{ --port=587 }
       . qq{ --user=$EMAIL_USERNAME_FROM }
       . qq{ --pass=$PLAINTEXT_PASSWORD }
       . qq{ --to=$sendTo }
       . qq{ --subject="DF output for $HOSTNAME, automatically sent by a cron job" }
       . qq{ --body-plain=$dfTemp }
    );


